bank/urls.py
from django.urls import path
from . import views

app_name = 'bank'

urlpatterns = [

    path('',views.Index, name='index'),

    #/bankaccount/<bankaccount_id>/
    path('bankaccount/<int:bankaccount_id>/', views.Detail, name='bankacc-detail'),

    path('bankaccount/<int:bankaccount_id>/delete/', views.Delete, name='bankacc-delete'),

    path('bankaccount/<int:bankaccount_id>/history/', views.TransactionHistory, name='bankacc-history'),

    path('bankaccount/add/', views.AddBankAccount, name='bankacc-add'),

    path('bankaccount/<int:bankaccount_id>/deposit/',views.Deposit, name='deposit'),

    path('bankaccount/<int:bankaccount_id>/withdraw/',views.Withdraw, name='withdraw'),

    path('bankaccount/<int:bankaccount_id>/transfer/',views.Transfer, name='transfer'),

    path('bankaccount/<int:bankaccount_id>/transfer/<int:tobankaccount_id>/',views.Transfer2, name='transfer2'),

    path('bankaccount/<int:bankaccount_id>/receipt/<int:transactionlog_id>/',views.Receipt, name='receipt'),

    path('bankaccount/<int:bankaccount_id>/favorite',views.FavoriteView, name='favorite'),

    path('bankaccount/<int:bankaccount_id>/favorite/add/', views.AddFavorite, name='favorite-add'),

    path('bankaccount/<int:bankaccount_id>/favorite/<int:favorite_id>/delete', views.DeleteFavorite, name='favorite-delete'),

    path('enterbankacc/',views.EnterBankAcc, name='enterbankacc'),

    path('logout/',views.logout_view, name='logout'),
]

se_ceBank/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('bank.urls')),
    path('',include('django.contrib.auth.urls'))
]

bank/models.py
from django.db import models
from accounts.models import BankAccount

# Create your models here.
class TransactionLog(models.Model):
    frombankaccount = models.ForeignKey(BankAccount,on_delete=models.SET_NULL,null=True,related_name='frombankaccount')
    tobankaccount = models.ForeignKey(BankAccount,on_delete=models.SET_NULL,null=True,related_name='tobankaccount')
    transactiontype = models.CharField(max_length=30) 
    number = models.CharField(max_length=30, unique = True)
    datetime = models.DateTimeField(auto_now_add=True)
    amount = models.DecimalField(
        default=0,
        max_digits=12,
        decimal_places=2
        ) 

class Favorite(models.Model):
    bankaccount = models.ForeignKey(BankAccount,on_delete=models.CASCADE,null=True,related_name='fav')
    favbankaccount = models.ForeignKey(BankAccount,on_delete=models.CASCADE,null=True,related_name='favbankaccount')
    name = models.CharField(max_length=100, default='')

bank/forms.py
from django import forms
from django.db import models

class TransferForm(forms.Form):
    bankaccnum = forms.CharField(label='Bank Account Number', max_length=20,widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'Enter Bank Account Number'}))

class Transfer2Form(forms.Form):
    amount = forms.DecimalField(label="Amount",decimal_places = 2,widget=forms.NumberInput(attrs={'class': 'form-control','placeholder':'Enter Amount'}))
    pin = forms.CharField()
    
class DepositAndWithdrawForm(forms.Form):
    amount = forms.DecimalField(label="Amount",decimal_places = 2,widget=forms.NumberInput(attrs={'class': 'form-control','placeholder':'Enter Amount'}))

class AddBankAccForm(forms.Form):
    bankaccnum = forms.CharField(label='Bank Account Number', max_length=20,widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'Enter Bank Account Number'}))
    pin = forms.CharField()

class EnterBankAccForm(forms.Form):
    bankaccnum = forms.CharField(label='Bank Account Number', max_length=20,widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'Enter Bank Account Number'}))

class AddFavoriteForm(forms.Form):
    bankaccnum = forms.CharField(label='Bank Account Number', max_length=20,widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'Enter Bank Account Number'}))
    name = forms.CharField(label='name', max_length=100,widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'Enter Name'}))

bank/views.py
from django.shortcuts import render
from django.db import models
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout
from django.views import generic
from django.views.generic import View
from .forms import TransferForm,Transfer2Form, AddBankAccForm,DepositAndWithdrawForm,EnterBankAccForm,AddFavoriteForm
from accounts.models import BankAccount
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import TransactionLog,Favorite

def logout_view(request):
    logout(request)
    return redirect('accounts:login')

@login_required
def Index(request):
    if request.user.is_staff:
        template_name = 'bank/staff_index.html'
        return render(request,template_name,{'staff':request.user})
    else:
        template_name = 'bank/index.html'
        all_bankaccounts = request.user.bankaccount_set.all()
        return render(request,template_name,{'all_bankaccounts':all_bankaccounts})

@login_required
def TransactionHistory(request,bankaccount_id):
        if request.user.is_staff:
            template_name = 'bank/staff_transactionhistory.html'
        else:
            template_name = 'bank/transactionhistory.html'
        bankaccount = BankAccount.objects.get(id=bankaccount_id)
        if (request.user.is_staff) or (request.user.bankaccount_set.get(id = bankaccount_id) is not None):
            fromtransactionlogs = bankaccount.frombankaccount.all()
            totransactionlogs = bankaccount.tobankaccount.all()
            all_transactionlogs = fromtransactionlogs | totransactionlogs
            all_transactionlogs = all_transactionlogs.distinct().order_by('-datetime')
            return render(request,template_name,{'all_transactionlogs':all_transactionlogs,'bankaccount_id':bankaccount_id})

@login_required
def Detail(request,bankaccount_id):
    if request.user.is_staff:
        template_name = 'bank/staff_detail.html'
        return render(request,template_name,{'bankaccount':BankAccount.objects.get(id = bankaccount_id),'bankaccount_id':bankaccount_id})
    if request.user.bankaccount_set.get(id = bankaccount_id) is not None:
        template_name = 'bank/detail.html'
        return render(request,template_name,{'bankaccount':BankAccount.objects.get(id = bankaccount_id),'bankaccount_id':bankaccount_id})

@login_required
def AddBankAccount(request):
    form = AddBankAccForm()
    template_name = 'bank/addbankacc.html'

    if request.method == 'POST':
        addbankaccForm = AddBankAccForm(request.POST)

        if addbankaccForm.is_valid():
            try:
                bankaccount = BankAccount.objects.get(number=addbankaccForm.cleaned_data['bankaccnum'])
            except ObjectDoesNotExist:
                return render(request,template_name,{'error_message':'Invalid Bank Account Number','form':form})

            pin = addbankaccForm.cleaned_data['pin']

            if bankaccount.pin == pin:
                    bankaccount.user.add(request.user)
                    bankaccount.save()
                    return redirect('bank:index') 
            else:
                return render(request,template_name,{'error_message':'Invalid PIN','form':form})
        else: 
            return render(request,template_name,{'form':form})

    else:
         return render(request,template_name,{'form':form})

@login_required
def Delete(request,bankaccount_id):
    bankaccount = BankAccount.objects.get(id=bankaccount_id)
    bankaccount.user.remove(request.user)
    bankaccount.save()
    return redirect('bank:index') 

@login_required
def Transfer(request,bankaccount_id):
    form = TransferForm()
    if request.user.is_staff:
        template_name = 'bank/staff_transfer.html'
    else:
        template_name = 'bank/transfer.html'
    frombankaccount = BankAccount.objects.get(id=bankaccount_id)
    if (request.user.is_staff) or (request.user.bankaccount_set.get(id = bankaccount_id) is not None):
        if request.method == 'POST':
            transferForm = TransferForm(request.POST)    
            if transferForm.is_valid():
                try:
                    tobankaccount = BankAccount.objects.get(number=transferForm.cleaned_data['bankaccnum'])
                except ObjectDoesNotExist:
                    return render(request,template_name,{'error_message':'Invalid Bank Account Number','form':form,'bankaccount':frombankaccount,'bankaccount_id':bankaccount_id})
                if tobankaccount == frombankaccount:
                    return render(request,template_name,{'error_message':"Can't Transfer to itself",'form':form,'bankaccount':frombankaccount,'bankaccount_id':bankaccount_id})   
                return redirect('bank:transfer2',bankaccount_id,tobankaccount.pk) 
            else: 
                return render(request,template_name,{'form':form,'bankaccount':frombankaccount,'bankaccount_id':bankaccount_id})
        else:
            return render(request,template_name,{'form':form, 'bankaccount':frombankaccount,'bankaccount_id':bankaccount_id})
    else:
        return redirect('bank:index') 

@login_required
def Transfer2(request,bankaccount_id,tobankaccount_id):
    form = Transfer2Form()
    if request.user.is_staff:
        template_name = 'bank/staff_transfer2.html'
    else:
        template_name = 'bank/transfer2.html'
    frombankaccount = BankAccount.objects.get(id=bankaccount_id)
    tobankaccount = BankAccount.objects.get(id=tobankaccount_id)
    if (request.user.is_staff) or (request.user.bankaccount_set.get(id = bankaccount_id) is not None):
        if request.method == 'POST':
            transfer2Form = Transfer2Form(request.POST)    
            if transfer2Form.is_valid():
                amount = transfer2Form.cleaned_data['amount']
                pin = transfer2Form.cleaned_data['pin']
                if tobankaccount == frombankaccount:
                    return render(request,template_name,{'error_message':"Can't Transfer to itself",'form':form,'bankaccount':frombankaccount,'tobankaccount':tobankaccount,'bankaccount_id':bankaccount_id})
                if amount > 0:
                    if(frombankaccount.pin == pin):
                        if(frombankaccount.balance >= amount):
                            frombankaccount.balance -= amount
                            tobankaccount.balance += amount
                            frombankaccount.save()
                            tobankaccount.save()
                            transactionlog = TransactionLog()
                            transactionlog.frombankaccount = frombankaccount
                            transactionlog.tobankaccount = tobankaccount
                            transactionlog.amount = amount
                            transactionlog.transactiontype = 'Transfer'
                            transactionlog.save()
                            transactionlog.number = str(transactionlog.pk).zfill(10)
                            transactionlog.save()
                            return redirect('bank:receipt',bankaccount_id,transactionlog.pk) 
                        else:
                            return render(request,template_name,{'error_message':'Not Enough Balance','form':form,'bankaccount':frombankaccount,'tobankaccount':tobankaccount,'bankaccount_id':bankaccount_id})
                    else:
                        return render(request,template_name,{'error_message':'Invalid PIN','form':form,'bankaccount':frombankaccount,'tobankaccount':tobankaccount,'bankaccount_id':bankaccount_id})
                else:
                    return render(request,template_name,{'error_message':'Amount Must be > 0','form':form,'bankaccount':frombankaccount,'tobankaccount':tobankaccount,'bankaccount_id':bankaccount_id})
            else: 
                return render(request,template_name,{'form':form,'bankaccount':frombankaccount,'tobankaccount':tobankaccount,'bankaccount_id':bankaccount_id})
        else: 
            return render(request,template_name,{'form':form,'bankaccount':frombankaccount,'tobankaccount':tobankaccount,'bankaccount_id':bankaccount_id})
    else:
        return redirect('bank:index') 

@staff_member_required
def Deposit(request,bankaccount_id):
    form = DepositAndWithdrawForm()
    template_name = 'bank/deposit.html'
    bankaccount = BankAccount.objects.get(id=bankaccount_id)

    if request.method == 'POST':
        depositForm = DepositAndWithdrawForm(request.POST)
        
        if depositForm.is_valid():
            amount = depositForm.cleaned_data['amount']

            if amount > 0:
                bankaccount.balance += amount
                bankaccount.save()
                transactionlog = TransactionLog()
                transactionlog.tobankaccount = bankaccount
                transactionlog.amount = amount
                transactionlog.transactiontype = 'Deposit'
                transactionlog.save()
                transactionlog.number = str(transactionlog.pk).zfill(10)
                transactionlog.save()
                return redirect('bank:receipt',bankaccount_id,transactionlog.pk) 
            else:
                return render(request,template_name,{'error_message':'Amount Must be > 0','form':form,'bankaccount':bankaccount,'bankaccount_id':bankaccount_id})
        else: 
            return render(request,template_name,{'form':form,'bankaccount':bankaccount,'bankaccount_id':bankaccount_id})

    else:
         return render(request,template_name,{'form':form,'bankaccount':bankaccount,'bankaccount_id':bankaccount_id})

@staff_member_required
def Withdraw(request,bankaccount_id):
    form = DepositAndWithdrawForm()
    template_name = 'bank/withdraw.html'

bank/templates/bank/favorite.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <title>Favorite</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

    <style>

        body{
            margin-top: 5rem;
            background-color: rgb(172, 170, 169);

        }

        h1{
            color:green;
        }   
        
        .back{
            width: 50px;
            height: 30px;
            background-image: url("leftArrow2.png");
            background-size: 50px 30px;
        }
        
        .account{
            margin-top: 50px;
            margin-left: 90px;
        }
   
        #acc1{
          border-radius: 100%;
          margin-left: 150px;
          margin-top: 50px;
          position:absolute;
        }

        #acc2{
          border-radius: 3%;
          margin-left: 950px;
          margin-top: 50px;
          position:absolute;

        }

        div.rightArrow2{
          width: 125px;
          height: 100px;
          background-image: url("rightArrow2.png");
          background-size: 125px 100px;
          margin-left: 685px;
          margin-top: 200px;
          position:absolute;
        }

        #nextBtn{
          margin-left: 1315px;
          margin-top: 510px;
          position: absolute;
        }

        .insertIMG{

        }
        .addIMG{
        
            margin-top:70px;
        }           

        p{
            font-family:'Lucida Sans Unicode';
            font-size: 20px;
            text-align: center;
        }

        .accNO{
            margin-top: 60px;
        }

        .reg{
            width: 250px;
            height: 250px;
            background-color: rgb(212, 212, 212);
            border-radius: 30px;
            margin-left: auto;
            margin-right: auto;
            margin-top: 30px;

        }

        h4{
            margin-top:-90px;
            color:white;
        }

        h6{
            margin-top:80px;
            overflow:hidden;
            white-space: nowrap;
            text-overflow:ellipsis;
            width: 80%;
            margin-left: auto;
            margin-right: auto;
        }
        

    </style>

</head>

<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top ">
        <a class="navbar-brand" href="\">
            <img src="{% static 'ceBank.png' %}" alt="logo" style="width:45px;">
        </a>
        <ul class="navbar-nav ">
            <li class="nav-item">
                <a class="nav-link" href="\bankaccount\{{bankaccount_id}}\favorite">Transfer</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="\bankaccount\{{bankaccount_id}}\history">Transaction
                    history</a>
            </li>
            <li class="nav-item">
                <a class="nav-link " href="\accounts\detail" style="margin-left:1040px">Account</a>
            </li>

        </ul>
        <a href="\logout" class="btn btn-outline-success btn-md ml-auto " id="okBtn">LOG OUT</a>
    </nav>


    <div class="bankaccounts-container container-fluid">
        <h1> Choose a favorite account</h1>
        <!-- FavoriteBankAccounts -->


        <div class="row text-center" style="display:flex; flex-wrap: wrap;">
            {% for favorite in all_favorites %}


            <div class="col-sm-3 ">
                <div class="thumbnail">
                    <div class="reg">
                        <br>
                        <img src="{% static 'account.png' %}" alt="logo" style="width:180px; height: 120px;">
                        <div class="caption">
                            <h4>{{ favorite.favbankaccount.number }}</h4>
                            <h6>{{ favorite.name }}</h6>


                            <!-- View Details -->
                            <a href="\bankaccount\{{bankaccount_id}}\transfer\{{favorite.favbankaccount.id}}" class="btn btn-success btn-sm"
                                role="button">Select</a>

                            <!-- Delete BankAccount -->
                            <form action="{% url 'bank:favorite-delete' bankaccount_id favorite.id %}" method="post"
                                style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="bankaccount_id" value="{{ bankaccount.id }}" />
                                <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModal">
                                    <img src="{% static 'delete.png' %}" style="width:15px; height: 20px;">
                                </button>
                                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                                    aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content" style="width:70%; margin-left:21%;">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Confirm?</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                Are you sure to delete this bank account?
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                                <button type="submit" class="btn btn-danger">Delete</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>



                </div>
            </div>
            {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}

            <div class="col-sm-3 ">
                <div class="reg">
                    <a href="\bankaccount\{{bankaccount_id}}\favorite\add">
                        <button type="button" class="btn btn-success " style="margin-top:105px; border-radius:100%;">
                            <img src="{% static 'plus.png' %}" style="width:20px; height: 20px; ">
                        </button>
                    </a>
                </div>
            </div>

            <div class="col-sm-3 ">
                <div class="reg">
                    <a href="\bankaccount\{{bankaccount_id}}\transfer\">
                        <button type="button" class="btn btn-light " style="margin-top:95px; border-radius:100%;">
                            <img src="{% static 'rightArrow2.png' %}" style="width:40px; height: 40px; ">
                        </button>
                    </a>
                </div>
            </div>

        </div>
    </div>
    </div>
</body>

</html>

bank/templates/bank/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <title>Account</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

    <link href="css/bootstrap-alert.css" rel="stylesheet">
    <script src="js/bootstrap-alert.js"></script>

    <script>
        function confirm() {
            BootstrapDialog.confirm('Are you sure you want to do this?');
        }
    </script>

    <style>

        body{
            margin-top: 5rem;
            background-color: rgb(172, 170, 169);

        }

        h1{
            color:green;
        }   
        
        .back{
            width: 50px;
            height: 30px;
            background-image: url("leftArrow2.png");
            background-size: 50px 30px;
        }
        
        .account{
            margin-top: 50px;
            margin-left: 90px;
        }
   
        #acc1{
          border-radius: 100%;
          margin-left: 150px;
          margin-top: 50px;
          position:absolute;
        }

        #acc2{
          border-radius: 3%;
          margin-left: 950px;
          margin-top: 50px;
          position:absolute;

        }

        div.rightArrow2{
          width: 125px;
          height: 100px;
          background-image: url("rightArrow2.png");
          background-size: 125px 100px;
          margin-left: 685px;
          margin-top: 200px;
          position:absolute;
        }

        #nextBtn{
          margin-left: 1315px;
          margin-top: 510px;
          position: absolute;
        }

        .insertIMG{

        }
        .addIMG{
        
            margin-top:70px;
        }           

        p{
            font-family:'Lucida Sans Unicode';
            font-size: 20px;
            text-align: center;
        }

        .accNO{
            margin-top: 60px;
        }

        .reg{
            width: 250px;
            height: 250px;
            background-color: rgb(212, 212, 212);
            border-radius: 30px;
            margin-left: auto;
            margin-right: auto;
            margin-top: 30px;

        }

        h4{
            margin-top:-90px;
            color:white;
        }

        h6{
            margin-top:80px;
            overflow:hidden;
            white-space: nowrap;
            text-overflow:ellipsis;
            width: 80%;
            margin-left: auto;
            margin-right: auto;
        }
        

    </style>

</head>

<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top ">
        <a class="navbar-brand" href="\">
            <img src="{% static 'ceBank.png' %}" alt="logo" style="width:45px;">
        </a>
        <ul class="navbar-nav ">
            <li class="nav-item">
                <a class="nav-link " href="\accounts\detail" style="margin-left:1260px">Account</a>
            </li>
        </ul>
        <a href="\logout" class="btn btn-outline-success btn-md ml-auto " id="okBtn">LOG OUT</a>
    </nav>


    <div class="bankaccounts-container container-fluid">
        <h1> Choose an account</h1>
        <!-- BankAccounts -->


        <div class="row text-center" style="display:flex; flex-wrap: wrap;">
            {% for bankaccount in all_bankaccounts %}


            <div class="col-sm-3 ">
                <div class="thumbnail">
                    <div class="reg">
                        <br>
                        <img src="{% static 'account.png' %}" alt="logo" style="width:180px; height: 120px;">
                        <div class="caption">
                            <h4>{{ bankaccount.number }}</h4>
                            <h6>{{ bankaccount.firstname }} {{ bankaccount.surname }}</h6>


                            <!-- View Details -->
                            <a href="{%url 'bank:bankacc-detail' bankaccount.id %}" class="btn btn-success btn-sm" role="button">Select</a>

                            <!-- Delete BankAccount -->
                            <form action="{% url 'bank:bankacc-delete' bankaccount.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="bankaccount_id" value="{{ bankaccount.id }}" />
                                <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModal">
                                    <img src="{% static 'delete.png' %}" style="width:15px; height: 20px;">
                                </button>

                                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" 
                                    aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content" style="width:70%; margin-left:21%;">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Confirm?</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                Are you sure to delete this bank account?
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                                <button type="submit" class="btn btn-danger">Delete</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>



                </div>
            </div>
            {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}

            <div class="col-sm-3 ">
                <div class="reg">
                    <a href="{% url 'bank:bankacc-add' %}">
                        <button type="button" class="btn btn-success " style="margin-top:105px; border-radius:100%;">
                            <img src="{% static 'plus.png' %}" style="width:20px; height: 20px; ">
                        </button>
                    </a>
                </div>
            </div>


        </div>
    </div>
    </div>
</body>

</html>